version: "3.9"
services:
  db:
    image: postgres:bullseye
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - "eUNI-API/.env"
    networks:
      - euni
  api:
    image: euni-api
    depends_on:
      - "db"
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: eUNI-API/Dockerfile
    env_file:
      - "eUNI-API/.env"
    networks:
      - euni
volumes:
  db:
networks:
  euni:
    driver: bridge
